// <auto-generated />
using System;
using IBANAccount.API.Persistance.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IBANAccount.API.Migrations
{
    [DbContext(typeof(SQLContext))]
    partial class SQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IBANAccount.API.Domain.Entities.Iban", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Code");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Country");

                    b.Property<int>("Length")
                        .HasColumnType("int")
                        .HasColumnName("Length");

                    b.HasKey("Id");

                    b.ToTable("Ibans", (string)null);
                });

            modelBuilder.Entity("IBANAccount.API.Domain.Entities.IbanImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date");

                    b.Property<int>("IbanId")
                        .HasColumnType("int")
                        .HasColumnName("IbanId");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImagePath");

                    b.HasKey("Id");

                    b.HasIndex("IbanId")
                        .IsUnique();

                    b.ToTable("IbanImages", (string)null);
                });

            modelBuilder.Entity("IBANAccount.API.Domain.Entities.UserIban", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IbanId")
                        .HasColumnType("int")
                        .HasColumnName("IbanId");

                    b.Property<string>("IbanNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IbanNumber");

                    b.Property<string>("IbanUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("IbanId");

                    b.ToTable("UserIbans", (string)null);
                });

            modelBuilder.Entity("IBANAccount.API.Domain.Entities.IbanImage", b =>
                {
                    b.HasOne("IBANAccount.API.Domain.Entities.Iban", null)
                        .WithOne("IbanImage")
                        .HasForeignKey("IBANAccount.API.Domain.Entities.IbanImage", "IbanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IBANAccount.API.Domain.Entities.UserIban", b =>
                {
                    b.HasOne("IBANAccount.API.Domain.Entities.Iban", "Iban")
                        .WithMany()
                        .HasForeignKey("IbanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iban");
                });

            modelBuilder.Entity("IBANAccount.API.Domain.Entities.Iban", b =>
                {
                    b.Navigation("IbanImage");
                });
#pragma warning restore 612, 618
        }
    }
}
