version: "3.8"
services:
  authdb:
   image: mcr.microsoft.com/mssql/server:2022-latest 
  auth.api:
   image: ${DOCKER_REGISTRY-}auth.api
   build: 
    context: .
    dockerfile: src/projects/AuthServer/AuthServer.API/Dockerfile
  socialmediadb:
   image: mcr.microsoft.com/mssql/server:2022-latest  
  socialmedia.api:
   image:  ${DOCKER_REGISTRY-}socialmedia.api
   build: 
    context: .
    dockerfile: src/projects/Services/SocialMedia/WebAPI/Dockerfile
  gamedb:
   image: mcr.microsoft.com/mssql/server:2022-latest   
  game.api:
   image:  ${DOCKER_REGISTRY-}game.api
   build: 
    context: .
    dockerfile: src/projects/Services/Game/WebAPI/Dockerfile 
  ibandb:
   image: mcr.microsoft.com/mssql/server:2022-latest  
  iban.api:
   image:  ${DOCKER_REGISTRY-}iban.api
   build: 
    context: .
    dockerfile: src/projects/Services/IBANAccount/IBANAccount.API/Dockerfile 
  cryptodb:
    image: mysql

  gateway.api:
     image: ${DOCKER_REGISTRY-}gateway.api_image
     build:
      context: .
      dockerfile: src/projects/Gateways/WebGateway/Dockerfile  

volumes:
  auth_volume:  
  socialmedia_volume:
  game_volume:
  iban_volume:
  crypto_volume:
  
  