version: "3.8"
services:
 
  authdb:
   container_name: AuthDb
   user: root
   ports:
    - 1433:1433
   volumes:
    - auth_volume:/var/opt/mssql
   environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password12* 
  auth.api:
   container_name: AuthAPI  
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SQLConnectionString=Server=authdb,1433;Database=AuthDb;User=sa;Password=Password12*" 
   depends_on:
    - authdb
   ports:
    - "5002:80"
 
  socialmediadb:
   container_name: SocialMediaDb
   user: root
   ports:
    - 1434:1433
   volumes:
    - socialmedia_volume:/var/opt/mssql
    
   environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password12* 
  
  socialmedia.api:
   container_name: SocialMediaAPI  
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SQLConnectionString=Server=socialmediadb,1433;Database=SocialMediaDb;User=sa;Password=Password12*" 
   depends_on:
    - socialmediadb
   volumes:
   - "socialmedia_volume:/app/wwwroot/images"
   ports:
    - "5010:80" 
  gamedb:
   container_name: GameDb
   user: root
   ports:
    - 1435:1433
   volumes:
    - game_volume:/var/opt/mssql
    
   environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password12*   
  game.api:
   container_name: GameAPI  
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SQLConnectionString=Server=gamedb,1433;Database=GameDb;User=sa;Password=Password12*" 
   depends_on:
    - gamedb
   volumes:
     - "game_volume:/app/wwwroot/images"
   ports:
    - "5011:80"
    - "7011:80"
  ibandb:
   container_name: IbanDb
   user: root
   ports:
    - 1436:1433
   volumes:
      - iban_volume:/var/opt/mssql
   environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password12* 
  cryptodb:
   container_name: CryptoDb
   user: root
   ports:
    - 3307:3306
   environment:
     - MYSQL_ROOT_PASSWORD=Password12*
     - MYSQL_DATABASE=crypto-db
   volumes:
     - crypto_volume:/var/lib/mysql   
  iban.api:
   container_name: IbanAPI  
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SQLConnectionString=Server=ibandb,1433;Database=IbanDb;User=sa;Password=Password12*;" 
   depends_on:
    - ibandb
   volumes:
     - "iban_volume:/app/wwwroot/images"
   ports:
    - "5012:80"
    - "7012:80"      
  gateway.api:
     container_name: gateway.api
     environment:
      - ASPNETCORE_ENVIRONMENT=Production
     ports:
        - 5000:80   