version: "3.8"
services:
  authdb:
   container_name: AuthDb
   user: root
   ports:
    - 1434:1433
   volumes:
    - auth_volume:/var/opt/mssql
   environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password12* 
  auth.api:
   container_name: AuthAPI  
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SQLConnectionString=Server=authdb,1434;Database=authdb;User=sa;Password=Password12*" 
   depends_on:
    - authdb
   ports:
    - 5002:80
     