// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance.Contexts;

#nullable disable

namespace Persistance.Migrations
{
    [DbContext(typeof(SQLContext))]
    partial class SQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Concrete.Entities.UserBiography", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BiographyDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserBiographies");
                });

            modelBuilder.Entity("Domain.Concrete.Entities.UserImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserImages");
                });

            modelBuilder.Entity("Domain.Concrete.Entities.UserTelephoneCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CountryCode");

                    b.Property<string>("CountryDialCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CountryDialCode");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CountryName");

                    b.HasKey("Id");

                    b.ToTable("UserTelephoneCountries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "AF",
                            CountryDialCode = "+93",
                            CountryName = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "AL",
                            CountryDialCode = "+355",
                            CountryName = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "DZ",
                            CountryDialCode = "+213",
                            CountryName = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "AD",
                            CountryDialCode = "+376",
                            CountryName = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            CountryCode = "AO",
                            CountryDialCode = "+244",
                            CountryName = "Angola"
                        },
                        new
                        {
                            Id = 6,
                            CountryCode = "AG",
                            CountryDialCode = "+1",
                            CountryName = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 7,
                            CountryCode = "AR",
                            CountryDialCode = "+54",
                            CountryName = "Argentina"
                        },
                        new
                        {
                            Id = 8,
                            CountryCode = "AM",
                            CountryDialCode = "+374",
                            CountryName = "Armenia"
                        },
                        new
                        {
                            Id = 9,
                            CountryCode = "AU",
                            CountryDialCode = "+61",
                            CountryName = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            CountryCode = "AT",
                            CountryDialCode = "+43",
                            CountryName = "Austria"
                        },
                        new
                        {
                            Id = 11,
                            CountryCode = "AZ",
                            CountryDialCode = "+994",
                            CountryName = "Azerbaijan"
                        },
                        new
                        {
                            Id = 12,
                            CountryCode = "BS",
                            CountryDialCode = "+1",
                            CountryName = "Bahamas"
                        },
                        new
                        {
                            Id = 13,
                            CountryCode = "BH",
                            CountryDialCode = "+973",
                            CountryName = "Bahrain"
                        },
                        new
                        {
                            Id = 14,
                            CountryCode = "BD",
                            CountryDialCode = "+880",
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            Id = 15,
                            CountryCode = "BB",
                            CountryDialCode = "+1",
                            CountryName = "Barbados"
                        },
                        new
                        {
                            Id = 16,
                            CountryCode = "BY",
                            CountryDialCode = "+375",
                            CountryName = "Belarus"
                        },
                        new
                        {
                            Id = 17,
                            CountryCode = "BE",
                            CountryDialCode = "+32",
                            CountryName = "Belgium"
                        },
                        new
                        {
                            Id = 18,
                            CountryCode = "BZ",
                            CountryDialCode = "+501",
                            CountryName = "Belize"
                        },
                        new
                        {
                            Id = 19,
                            CountryCode = "BJ",
                            CountryDialCode = "+229",
                            CountryName = "Benin"
                        },
                        new
                        {
                            Id = 20,
                            CountryCode = "BT",
                            CountryDialCode = "+975",
                            CountryName = "Bhutan"
                        },
                        new
                        {
                            Id = 21,
                            CountryCode = "BO",
                            CountryDialCode = "+591",
                            CountryName = "Bolivia"
                        },
                        new
                        {
                            Id = 22,
                            CountryCode = "BA",
                            CountryDialCode = "+387",
                            CountryName = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 23,
                            CountryCode = "BW",
                            CountryDialCode = "+267",
                            CountryName = "Botswana"
                        },
                        new
                        {
                            Id = 24,
                            CountryCode = "BR",
                            CountryDialCode = "+55",
                            CountryName = "Brazil"
                        },
                        new
                        {
                            Id = 25,
                            CountryCode = "BN",
                            CountryDialCode = "+673",
                            CountryName = "Brunei"
                        },
                        new
                        {
                            Id = 26,
                            CountryCode = "BG",
                            CountryDialCode = "+359",
                            CountryName = "Bulgaria"
                        },
                        new
                        {
                            Id = 27,
                            CountryCode = "BF",
                            CountryDialCode = "+226",
                            CountryName = "Burkina Faso"
                        },
                        new
                        {
                            Id = 28,
                            CountryCode = "BI",
                            CountryDialCode = "+257",
                            CountryName = "Burundi"
                        },
                        new
                        {
                            Id = 29,
                            CountryCode = "CV",
                            CountryDialCode = "+238",
                            CountryName = "Cabo Verde"
                        },
                        new
                        {
                            Id = 30,
                            CountryCode = "KH",
                            CountryDialCode = "+855",
                            CountryName = "Cambodia"
                        },
                        new
                        {
                            Id = 31,
                            CountryCode = "CM",
                            CountryDialCode = "+237",
                            CountryName = "Cameroon"
                        },
                        new
                        {
                            Id = 32,
                            CountryCode = "CA",
                            CountryDialCode = "+1",
                            CountryName = "Canada"
                        },
                        new
                        {
                            Id = 33,
                            CountryCode = "CF",
                            CountryDialCode = "+236",
                            CountryName = "Central African Republic"
                        },
                        new
                        {
                            Id = 34,
                            CountryCode = "TD",
                            CountryDialCode = "+235",
                            CountryName = "Chad"
                        },
                        new
                        {
                            Id = 35,
                            CountryCode = "CL",
                            CountryDialCode = "+56",
                            CountryName = "Chile"
                        },
                        new
                        {
                            Id = 36,
                            CountryCode = "CN",
                            CountryDialCode = "+86",
                            CountryName = "China"
                        },
                        new
                        {
                            Id = 37,
                            CountryCode = "CO",
                            CountryDialCode = "+57",
                            CountryName = "Colombia"
                        },
                        new
                        {
                            Id = 38,
                            CountryCode = "KM",
                            CountryDialCode = "+269",
                            CountryName = "Comoros"
                        },
                        new
                        {
                            Id = 39,
                            CountryCode = "CG",
                            CountryDialCode = "+242",
                            CountryName = "Congo"
                        },
                        new
                        {
                            Id = 40,
                            CountryCode = "CR",
                            CountryDialCode = "+506",
                            CountryName = "Costa Rica"
                        },
                        new
                        {
                            Id = 41,
                            CountryCode = "HR",
                            CountryDialCode = "+385",
                            CountryName = "Croatia"
                        },
                        new
                        {
                            Id = 42,
                            CountryCode = "CU",
                            CountryDialCode = "+53",
                            CountryName = "Cuba"
                        },
                        new
                        {
                            Id = 43,
                            CountryCode = "CY",
                            CountryDialCode = "+357",
                            CountryName = "Cyprus"
                        },
                        new
                        {
                            Id = 44,
                            CountryCode = "CZ",
                            CountryDialCode = "+420",
                            CountryName = "Czech Republic"
                        },
                        new
                        {
                            Id = 45,
                            CountryCode = "DK",
                            CountryDialCode = "+45",
                            CountryName = "Denmark"
                        },
                        new
                        {
                            Id = 46,
                            CountryCode = "DJ",
                            CountryDialCode = "+253",
                            CountryName = "Djibouti"
                        },
                        new
                        {
                            Id = 47,
                            CountryCode = "DM",
                            CountryDialCode = "+1",
                            CountryName = "Dominica"
                        },
                        new
                        {
                            Id = 48,
                            CountryCode = "DO",
                            CountryDialCode = "+1",
                            CountryName = "Dominican Republic"
                        },
                        new
                        {
                            Id = 49,
                            CountryCode = "EC",
                            CountryDialCode = "+593",
                            CountryName = "Ecuador"
                        },
                        new
                        {
                            Id = 50,
                            CountryCode = "EG",
                            CountryDialCode = "+20",
                            CountryName = "Egypt"
                        },
                        new
                        {
                            Id = 51,
                            CountryCode = "SV",
                            CountryDialCode = "+503",
                            CountryName = "El Salvador"
                        },
                        new
                        {
                            Id = 52,
                            CountryCode = "GQ",
                            CountryDialCode = "+240",
                            CountryName = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 53,
                            CountryCode = "ER",
                            CountryDialCode = "+291",
                            CountryName = "Eritrea"
                        },
                        new
                        {
                            Id = 54,
                            CountryCode = "EE",
                            CountryDialCode = "+372",
                            CountryName = "Estonia"
                        },
                        new
                        {
                            Id = 55,
                            CountryCode = "SZ",
                            CountryDialCode = "+268",
                            CountryName = "Eswatini"
                        },
                        new
                        {
                            Id = 56,
                            CountryCode = "ET",
                            CountryDialCode = "+251",
                            CountryName = "Ethiopia"
                        },
                        new
                        {
                            Id = 57,
                            CountryCode = "FJ",
                            CountryDialCode = "+679",
                            CountryName = "Fiji"
                        },
                        new
                        {
                            Id = 58,
                            CountryCode = "FI",
                            CountryDialCode = "+358",
                            CountryName = "Finland"
                        },
                        new
                        {
                            Id = 59,
                            CountryCode = "FR",
                            CountryDialCode = "+33",
                            CountryName = "France"
                        },
                        new
                        {
                            Id = 60,
                            CountryCode = "GA",
                            CountryDialCode = "+241",
                            CountryName = "Gabon"
                        },
                        new
                        {
                            Id = 61,
                            CountryCode = "GM",
                            CountryDialCode = "+220",
                            CountryName = "Gambia"
                        },
                        new
                        {
                            Id = 62,
                            CountryCode = "GE",
                            CountryDialCode = "+995",
                            CountryName = "Georgia"
                        },
                        new
                        {
                            Id = 63,
                            CountryCode = "DE",
                            CountryDialCode = "+49",
                            CountryName = "Germany"
                        },
                        new
                        {
                            Id = 64,
                            CountryCode = "GH",
                            CountryDialCode = "+233",
                            CountryName = "Ghana"
                        },
                        new
                        {
                            Id = 65,
                            CountryCode = "GR",
                            CountryDialCode = "+30",
                            CountryName = "Greece"
                        },
                        new
                        {
                            Id = 66,
                            CountryCode = "GD",
                            CountryDialCode = "+1",
                            CountryName = "Grenada"
                        },
                        new
                        {
                            Id = 67,
                            CountryCode = "GT",
                            CountryDialCode = "+502",
                            CountryName = "Guatemala"
                        },
                        new
                        {
                            Id = 68,
                            CountryCode = "GN",
                            CountryDialCode = "+224",
                            CountryName = "Guinea"
                        },
                        new
                        {
                            Id = 69,
                            CountryCode = "GW",
                            CountryDialCode = "+245",
                            CountryName = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 70,
                            CountryCode = "GY",
                            CountryDialCode = "+592",
                            CountryName = "Guyana"
                        },
                        new
                        {
                            Id = 71,
                            CountryCode = "HT",
                            CountryDialCode = "+509",
                            CountryName = "Haiti"
                        },
                        new
                        {
                            Id = 72,
                            CountryCode = "HN",
                            CountryDialCode = "+504",
                            CountryName = "Honduras"
                        },
                        new
                        {
                            Id = 73,
                            CountryCode = "HU",
                            CountryDialCode = "+36",
                            CountryName = "Hungary"
                        },
                        new
                        {
                            Id = 74,
                            CountryCode = "IS",
                            CountryDialCode = "+354",
                            CountryName = "Iceland"
                        },
                        new
                        {
                            Id = 75,
                            CountryCode = "IN",
                            CountryDialCode = "+91",
                            CountryName = "India"
                        },
                        new
                        {
                            Id = 76,
                            CountryCode = "ID",
                            CountryDialCode = "+62",
                            CountryName = "Indonesia"
                        },
                        new
                        {
                            Id = 77,
                            CountryCode = "IR",
                            CountryDialCode = "+98",
                            CountryName = "Iran"
                        },
                        new
                        {
                            Id = 78,
                            CountryCode = "IQ",
                            CountryDialCode = "+964",
                            CountryName = "Iraq"
                        },
                        new
                        {
                            Id = 79,
                            CountryCode = "IE",
                            CountryDialCode = "+353",
                            CountryName = "Ireland"
                        },
                        new
                        {
                            Id = 80,
                            CountryCode = "IL",
                            CountryDialCode = "+972",
                            CountryName = "Israel"
                        },
                        new
                        {
                            Id = 81,
                            CountryCode = "IT",
                            CountryDialCode = "+39",
                            CountryName = "Italy"
                        },
                        new
                        {
                            Id = 82,
                            CountryCode = "JM",
                            CountryDialCode = "+1",
                            CountryName = "Jamaica"
                        },
                        new
                        {
                            Id = 83,
                            CountryCode = "JP",
                            CountryDialCode = "+81",
                            CountryName = "Japan"
                        },
                        new
                        {
                            Id = 84,
                            CountryCode = "JO",
                            CountryDialCode = "+962",
                            CountryName = "Jordan"
                        },
                        new
                        {
                            Id = 85,
                            CountryCode = "KZ",
                            CountryDialCode = "+7",
                            CountryName = "Kazakhstan"
                        },
                        new
                        {
                            Id = 86,
                            CountryCode = "KE",
                            CountryDialCode = "+254",
                            CountryName = "Kenya"
                        },
                        new
                        {
                            Id = 87,
                            CountryCode = "KI",
                            CountryDialCode = "+686",
                            CountryName = "Kiribati"
                        },
                        new
                        {
                            Id = 88,
                            CountryCode = "KP",
                            CountryDialCode = "+850",
                            CountryName = "Korea, North"
                        },
                        new
                        {
                            Id = 89,
                            CountryCode = "KR",
                            CountryDialCode = "+82",
                            CountryName = "Korea, South"
                        },
                        new
                        {
                            Id = 90,
                            CountryCode = "KW",
                            CountryDialCode = "+965",
                            CountryName = "Kuwait"
                        },
                        new
                        {
                            Id = 91,
                            CountryCode = "KG",
                            CountryDialCode = "+996",
                            CountryName = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 92,
                            CountryCode = "LA",
                            CountryDialCode = "+856",
                            CountryName = "Laos"
                        },
                        new
                        {
                            Id = 93,
                            CountryCode = "LV",
                            CountryDialCode = "+371",
                            CountryName = "Latvia"
                        },
                        new
                        {
                            Id = 94,
                            CountryCode = "LB",
                            CountryDialCode = "+961",
                            CountryName = "Lebanon"
                        },
                        new
                        {
                            Id = 95,
                            CountryCode = "LS",
                            CountryDialCode = "+266",
                            CountryName = "Lesotho"
                        },
                        new
                        {
                            Id = 96,
                            CountryCode = "LR",
                            CountryDialCode = "+231",
                            CountryName = "Liberia"
                        },
                        new
                        {
                            Id = 97,
                            CountryCode = "LY",
                            CountryDialCode = "+218",
                            CountryName = "Libya"
                        },
                        new
                        {
                            Id = 98,
                            CountryCode = "LI",
                            CountryDialCode = "+423",
                            CountryName = "Liechtenstein"
                        },
                        new
                        {
                            Id = 99,
                            CountryCode = "LT",
                            CountryDialCode = "+370",
                            CountryName = "Lithuania"
                        },
                        new
                        {
                            Id = 100,
                            CountryCode = "LU",
                            CountryDialCode = "+352",
                            CountryName = "Luxembourg"
                        },
                        new
                        {
                            Id = 101,
                            CountryCode = "MG",
                            CountryDialCode = "+261",
                            CountryName = "Madagascar"
                        },
                        new
                        {
                            Id = 102,
                            CountryCode = "MW",
                            CountryDialCode = "+265",
                            CountryName = "Malawi"
                        },
                        new
                        {
                            Id = 103,
                            CountryCode = "MY",
                            CountryDialCode = "+60",
                            CountryName = "Malaysia"
                        },
                        new
                        {
                            Id = 104,
                            CountryCode = "MV",
                            CountryDialCode = "+960",
                            CountryName = "Maldives"
                        },
                        new
                        {
                            Id = 105,
                            CountryCode = "ML",
                            CountryDialCode = "+223",
                            CountryName = "Mali"
                        },
                        new
                        {
                            Id = 106,
                            CountryCode = "MT",
                            CountryDialCode = "+356",
                            CountryName = "Malta"
                        },
                        new
                        {
                            Id = 107,
                            CountryCode = "MH",
                            CountryDialCode = "+692",
                            CountryName = "Marshall Islands"
                        },
                        new
                        {
                            Id = 108,
                            CountryCode = "MR",
                            CountryDialCode = "+222",
                            CountryName = "Mauritania"
                        },
                        new
                        {
                            Id = 109,
                            CountryCode = "MU",
                            CountryDialCode = "+230",
                            CountryName = "Mauritius"
                        },
                        new
                        {
                            Id = 110,
                            CountryCode = "MX",
                            CountryDialCode = "+52",
                            CountryName = "Mexico"
                        },
                        new
                        {
                            Id = 111,
                            CountryCode = "FM",
                            CountryDialCode = "+691",
                            CountryName = "Micronesia"
                        },
                        new
                        {
                            Id = 112,
                            CountryCode = "MD",
                            CountryDialCode = "+373",
                            CountryName = "Moldova"
                        },
                        new
                        {
                            Id = 113,
                            CountryCode = "MC",
                            CountryDialCode = "+377",
                            CountryName = "Monaco"
                        },
                        new
                        {
                            Id = 114,
                            CountryCode = "MN",
                            CountryDialCode = "+976",
                            CountryName = "Mongolia"
                        },
                        new
                        {
                            Id = 115,
                            CountryCode = "ME",
                            CountryDialCode = "+382",
                            CountryName = "Montenegro"
                        },
                        new
                        {
                            Id = 116,
                            CountryCode = "MA",
                            CountryDialCode = "+212",
                            CountryName = "Morocco"
                        },
                        new
                        {
                            Id = 117,
                            CountryCode = "MZ",
                            CountryDialCode = "+258",
                            CountryName = "Mozambique"
                        },
                        new
                        {
                            Id = 118,
                            CountryCode = "MM",
                            CountryDialCode = "+95",
                            CountryName = "Myanmar"
                        },
                        new
                        {
                            Id = 119,
                            CountryCode = "NA",
                            CountryDialCode = "+264",
                            CountryName = "Namibia"
                        },
                        new
                        {
                            Id = 120,
                            CountryCode = "NR",
                            CountryDialCode = "+674",
                            CountryName = "Nauru"
                        },
                        new
                        {
                            Id = 121,
                            CountryCode = "NP",
                            CountryDialCode = "+977",
                            CountryName = "Nepal"
                        },
                        new
                        {
                            Id = 122,
                            CountryCode = "NL",
                            CountryDialCode = "+31",
                            CountryName = "Netherlands"
                        },
                        new
                        {
                            Id = 123,
                            CountryCode = "NZ",
                            CountryDialCode = "+64",
                            CountryName = "New Zealand"
                        },
                        new
                        {
                            Id = 124,
                            CountryCode = "NI",
                            CountryDialCode = "+505",
                            CountryName = "Nicaragua"
                        },
                        new
                        {
                            Id = 125,
                            CountryCode = "NE",
                            CountryDialCode = "+227",
                            CountryName = "Niger"
                        },
                        new
                        {
                            Id = 126,
                            CountryCode = "NG",
                            CountryDialCode = "+234",
                            CountryName = "Nigeria"
                        },
                        new
                        {
                            Id = 127,
                            CountryCode = "MK",
                            CountryDialCode = "+389",
                            CountryName = "North Macedonia"
                        },
                        new
                        {
                            Id = 128,
                            CountryCode = "NO",
                            CountryDialCode = "+47",
                            CountryName = "Norway"
                        },
                        new
                        {
                            Id = 129,
                            CountryCode = "OM",
                            CountryDialCode = "+968",
                            CountryName = "Oman"
                        },
                        new
                        {
                            Id = 130,
                            CountryCode = "PK",
                            CountryDialCode = "+92",
                            CountryName = "Pakistan"
                        },
                        new
                        {
                            Id = 131,
                            CountryCode = "PW",
                            CountryDialCode = "+680",
                            CountryName = "Palau"
                        },
                        new
                        {
                            Id = 132,
                            CountryCode = "PS",
                            CountryDialCode = "+970",
                            CountryName = "Palestine"
                        },
                        new
                        {
                            Id = 133,
                            CountryCode = "PA",
                            CountryDialCode = "+507",
                            CountryName = "Panama"
                        },
                        new
                        {
                            Id = 134,
                            CountryCode = "PG",
                            CountryDialCode = "+675",
                            CountryName = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 135,
                            CountryCode = "PY",
                            CountryDialCode = "+595",
                            CountryName = "Paraguay"
                        },
                        new
                        {
                            Id = 136,
                            CountryCode = "PE",
                            CountryDialCode = "+51",
                            CountryName = "Peru"
                        },
                        new
                        {
                            Id = 137,
                            CountryCode = "PH",
                            CountryDialCode = "+63",
                            CountryName = "Philippines"
                        },
                        new
                        {
                            Id = 138,
                            CountryCode = "PL",
                            CountryDialCode = "+48",
                            CountryName = "Poland"
                        },
                        new
                        {
                            Id = 139,
                            CountryCode = "PT",
                            CountryDialCode = "+351",
                            CountryName = "Portugal"
                        },
                        new
                        {
                            Id = 140,
                            CountryCode = "QA",
                            CountryDialCode = "+974",
                            CountryName = "Qatar"
                        },
                        new
                        {
                            Id = 141,
                            CountryCode = "RO",
                            CountryDialCode = "+40",
                            CountryName = "Romania"
                        },
                        new
                        {
                            Id = 142,
                            CountryCode = "RU",
                            CountryDialCode = "+7",
                            CountryName = "Russia"
                        },
                        new
                        {
                            Id = 143,
                            CountryCode = "RW",
                            CountryDialCode = "+250",
                            CountryName = "Rwanda"
                        },
                        new
                        {
                            Id = 144,
                            CountryCode = "KN",
                            CountryDialCode = "+1",
                            CountryName = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 145,
                            CountryCode = "LC",
                            CountryDialCode = "+1",
                            CountryName = "Saint Lucia"
                        },
                        new
                        {
                            Id = 146,
                            CountryCode = "VC",
                            CountryDialCode = "+1",
                            CountryName = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 147,
                            CountryCode = "WS",
                            CountryDialCode = "+685",
                            CountryName = "Samoa"
                        },
                        new
                        {
                            Id = 148,
                            CountryCode = "SM",
                            CountryDialCode = "+378",
                            CountryName = "San Marino"
                        },
                        new
                        {
                            Id = 149,
                            CountryCode = "ST",
                            CountryDialCode = "+239",
                            CountryName = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 150,
                            CountryCode = "SA",
                            CountryDialCode = "+966",
                            CountryName = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 151,
                            CountryCode = "SN",
                            CountryDialCode = "+221",
                            CountryName = "Senegal"
                        },
                        new
                        {
                            Id = 152,
                            CountryCode = "RS",
                            CountryDialCode = "+381",
                            CountryName = "Serbia"
                        },
                        new
                        {
                            Id = 153,
                            CountryCode = "SC",
                            CountryDialCode = "+248",
                            CountryName = "Seychelles"
                        },
                        new
                        {
                            Id = 154,
                            CountryCode = "SL",
                            CountryDialCode = "+232",
                            CountryName = "Sierra Leone"
                        },
                        new
                        {
                            Id = 155,
                            CountryCode = "SG",
                            CountryDialCode = "+65",
                            CountryName = "Singapore"
                        },
                        new
                        {
                            Id = 156,
                            CountryCode = "SK",
                            CountryDialCode = "+421",
                            CountryName = "Slovakia"
                        },
                        new
                        {
                            Id = 157,
                            CountryCode = "SI",
                            CountryDialCode = "+386",
                            CountryName = "Slovenia"
                        },
                        new
                        {
                            Id = 158,
                            CountryCode = "SB",
                            CountryDialCode = "+677",
                            CountryName = "Solomon Islands"
                        },
                        new
                        {
                            Id = 159,
                            CountryCode = "SO",
                            CountryDialCode = "+252",
                            CountryName = "Somalia"
                        },
                        new
                        {
                            Id = 160,
                            CountryCode = "ZA",
                            CountryDialCode = "+27",
                            CountryName = "South Africa"
                        },
                        new
                        {
                            Id = 161,
                            CountryCode = "SS",
                            CountryDialCode = "+211",
                            CountryName = "South Sudan"
                        },
                        new
                        {
                            Id = 162,
                            CountryCode = "ES",
                            CountryDialCode = "+34",
                            CountryName = "Spain"
                        },
                        new
                        {
                            Id = 163,
                            CountryCode = "LK",
                            CountryDialCode = "+94",
                            CountryName = "Sri Lanka"
                        },
                        new
                        {
                            Id = 164,
                            CountryCode = "SD",
                            CountryDialCode = "+249",
                            CountryName = "Sudan"
                        },
                        new
                        {
                            Id = 165,
                            CountryCode = "SR",
                            CountryDialCode = "+597",
                            CountryName = "SuriCountryName"
                        },
                        new
                        {
                            Id = 166,
                            CountryCode = "SE",
                            CountryDialCode = "+46",
                            CountryName = "Sweden"
                        },
                        new
                        {
                            Id = 167,
                            CountryCode = "CH",
                            CountryDialCode = "+41",
                            CountryName = "Switzerland"
                        },
                        new
                        {
                            Id = 168,
                            CountryCode = "SY",
                            CountryDialCode = "+963",
                            CountryName = "Syria"
                        },
                        new
                        {
                            Id = 169,
                            CountryCode = "TW",
                            CountryDialCode = "+886",
                            CountryName = "Taiwan"
                        },
                        new
                        {
                            Id = 170,
                            CountryCode = "TJ",
                            CountryDialCode = "+992",
                            CountryName = "Tajikistan"
                        },
                        new
                        {
                            Id = 171,
                            CountryCode = "TZ",
                            CountryDialCode = "+255",
                            CountryName = "Tanzania"
                        },
                        new
                        {
                            Id = 172,
                            CountryCode = "TH",
                            CountryDialCode = "+66",
                            CountryName = "Thailand"
                        },
                        new
                        {
                            Id = 173,
                            CountryCode = "TL",
                            CountryDialCode = "+670",
                            CountryName = "Timor-Leste"
                        },
                        new
                        {
                            Id = 174,
                            CountryCode = "TG",
                            CountryDialCode = "+228",
                            CountryName = "Togo"
                        },
                        new
                        {
                            Id = 175,
                            CountryCode = "TO",
                            CountryDialCode = "+676",
                            CountryName = "Tonga"
                        },
                        new
                        {
                            Id = 176,
                            CountryCode = "TT",
                            CountryDialCode = "+1",
                            CountryName = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 177,
                            CountryCode = "TN",
                            CountryDialCode = "+216",
                            CountryName = "Tunisia"
                        },
                        new
                        {
                            Id = 178,
                            CountryCode = "TR",
                            CountryDialCode = "+90",
                            CountryName = "Turkey"
                        },
                        new
                        {
                            Id = 179,
                            CountryCode = "TM",
                            CountryDialCode = "+993",
                            CountryName = "Turkmenistan"
                        },
                        new
                        {
                            Id = 180,
                            CountryCode = "TV",
                            CountryDialCode = "+688",
                            CountryName = "Tuvalu"
                        },
                        new
                        {
                            Id = 181,
                            CountryCode = "UG",
                            CountryDialCode = "+256",
                            CountryName = "Uganda"
                        },
                        new
                        {
                            Id = 182,
                            CountryCode = "UA",
                            CountryDialCode = "+380",
                            CountryName = "Ukraine"
                        },
                        new
                        {
                            Id = 183,
                            CountryCode = "AE",
                            CountryDialCode = "+971",
                            CountryName = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 184,
                            CountryCode = "GB",
                            CountryDialCode = "+44",
                            CountryName = "United Kingdom"
                        },
                        new
                        {
                            Id = 185,
                            CountryCode = "US",
                            CountryDialCode = "+1",
                            CountryName = "United States"
                        },
                        new
                        {
                            Id = 186,
                            CountryCode = "UY",
                            CountryDialCode = "+598",
                            CountryName = "Uruguay"
                        },
                        new
                        {
                            Id = 187,
                            CountryCode = "UZ",
                            CountryDialCode = "+998",
                            CountryName = "Uzbekistan"
                        },
                        new
                        {
                            Id = 188,
                            CountryCode = "VU",
                            CountryDialCode = "+678",
                            CountryName = "Vanuatu"
                        },
                        new
                        {
                            Id = 189,
                            CountryCode = "VA",
                            CountryDialCode = "+39",
                            CountryName = "Vatican City"
                        },
                        new
                        {
                            Id = 190,
                            CountryCode = "VE",
                            CountryDialCode = "+58",
                            CountryName = "Venezuela"
                        },
                        new
                        {
                            Id = 191,
                            CountryCode = "VN",
                            CountryDialCode = "+84",
                            CountryName = "Vietnam"
                        },
                        new
                        {
                            Id = 192,
                            CountryCode = "YE",
                            CountryDialCode = "+967",
                            CountryName = "Yemen"
                        },
                        new
                        {
                            Id = 193,
                            CountryCode = "ZM",
                            CountryDialCode = "+260",
                            CountryName = "Zambia"
                        },
                        new
                        {
                            Id = 194,
                            CountryCode = "ZW",
                            CountryDialCode = "+263",
                            CountryName = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Domain.Concrete.Entities.UserTelephoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TelephoneNumber");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserId");

                    b.Property<int>("UserTelephoneCountryId")
                        .HasColumnType("int")
                        .HasColumnName("UserTelephoneCountryId");

                    b.Property<int>("UserTelephoneTypeId")
                        .HasColumnType("int")
                        .HasColumnName("UserTelephoneTypeId");

                    b.HasKey("Id");

                    b.HasIndex("UserTelephoneCountryId")
                        .IsUnique();

                    b.HasIndex("UserTelephoneTypeId");

                    b.ToTable("UserTelephoneNumbers", (string)null);
                });

            modelBuilder.Entity("Domain.Concrete.Entities.UserTelephoneType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TelephoneType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserTelephoneTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TelephoneType = "Kişisel Telefonu"
                        },
                        new
                        {
                            Id = 2,
                            TelephoneType = "İş Telefonu"
                        },
                        new
                        {
                            Id = 3,
                            TelephoneType = "Okul Telefonu"
                        });
                });

            modelBuilder.Entity("Domain.Concrete.Entities.UserTelephoneNumber", b =>
                {
                    b.HasOne("Domain.Concrete.Entities.UserTelephoneCountry", "UserTelephoneCountry")
                        .WithOne()
                        .HasForeignKey("Domain.Concrete.Entities.UserTelephoneNumber", "UserTelephoneCountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Concrete.Entities.UserTelephoneType", "UserTelephoneType")
                        .WithMany()
                        .HasForeignKey("UserTelephoneTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserTelephoneCountry");

                    b.Navigation("UserTelephoneType");
                });
#pragma warning restore 612, 618
        }
    }
}
