// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Persistance.Contexts;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(SQLDbContext))]
    partial class SQLDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebAPI.Domain.Entities.Crypto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CryptoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CryptoName");

                    b.HasKey("Id");

                    b.ToTable("Cryptos", (string)null);
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.CryptoImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CryptoId")
                        .HasColumnType("int")
                        .HasColumnName("CryptoId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImagePath");

                    b.HasKey("Id");

                    b.HasIndex("CryptoId")
                        .IsUnique();

                    b.ToTable("CryptoImages", (string)null);
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.UserCyrpto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CryptoId")
                        .HasColumnType("int")
                        .HasColumnName("CryptoId");

                    b.Property<string>("CryptoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CryptoUrl");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CryptoId");

                    b.ToTable("UserCrypto", (string)null);
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.CryptoImage", b =>
                {
                    b.HasOne("WebAPI.Domain.Entities.Crypto", "Crypto")
                        .WithOne("CryptoImage")
                        .HasForeignKey("WebAPI.Domain.Entities.CryptoImage", "CryptoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crypto");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.UserCyrpto", b =>
                {
                    b.HasOne("WebAPI.Domain.Entities.Crypto", "Crypto")
                        .WithMany("UserCyrptos")
                        .HasForeignKey("CryptoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crypto");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Crypto", b =>
                {
                    b.Navigation("CryptoImage");

                    b.Navigation("UserCyrptos");
                });
#pragma warning restore 612, 618
        }
    }
}
